# Generated by Django 4.0.3 on 2022-08-30 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_alter_answer_author_alter_question_author'),
        ('pybo', '0005_answer_voter_question_voter_alter_answer_author_and_more'),
    ]

    operations = [
    ]
